# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin_success_handler:
        class: WildPartyBundle\Services\AuthenticationHandler
        arguments: [@router]

    sonata.user.admin.group:
        abstract: true
        public: false