<?php

namespace WildPartyBundle\Entity;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoireeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSoireesFutur()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('s')
            ->from($this->_entityName, 's')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('s.dateDebut >= :now')
            ->setParameter('now', new \DateTime('now'))
            ->orderBy('s.dateDebut', 'ASC');
        return $queryBuilder->getQuery()->getResult();
    }

    public function findSoireesPast()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('s')
            ->from($this->_entityName, 's')// Dans un repository, $this->_entityName est le namespace de l'entité gérée
            ->Where('s.dateDebut <= :now')
            ->setParameter('now', new \DateTime('now'))
            ->orderBy('s.dateDebut', 'ASC');
        return $queryBuilder->getQuery()->getResult();
    }
}
