<?php

namespace WildPartyBundle\Entity;

/**
 * SoireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoireeRepository extends \Doctrine\ORM\EntityRepository
{
}
