<?php

namespace WildPartyBundle\Entity;

use Doctrine\ORM\QueryBuilder;
/**
 * Utilisateur_soireeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateur_soireeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllSoireeByUser($user)
    {
        /*$qb = $this->createQueryBuilder('us')
            ->select('us.soiree_id')
        ;

        $query = $qb->getQuery();
        return $query->getResult();*/
    }
}