<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    public function __construct()
    {
        $this->enabled = true;
    }
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $soiree;


    /**
     * Add soiree
     *
     * @param \WildPartyBundle\Entity\Soiree $soiree
     *
     * @return User
     */
    public function addSoiree(\WildPartyBundle\Entity\Soiree $soiree)
    {
        $this->soiree[] = $soiree;

        return $this;
    }

    /**
     * Remove soiree
     *
     * @param \WildPartyBundle\Entity\Soiree $soiree
     */
    public function removeSoiree(\WildPartyBundle\Entity\Soiree $soiree)
    {
        $this->soiree->removeElement($soiree);
    }

    /**
     * Get soiree
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSoiree()
    {
        return $this->soiree;
    }
}
